[package]
name = "generate_waveform_image"
version = "0.1.0"
authors = ["barney <barney@gie.im>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.0"
rustfft = "6.0.0"
hound = "3.5.0"
rodio = "0.13.0"
